# Generated by Django 4.0.3 on 2022-07-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
