# Generated by Django 4.0.3 on 2022-07-28 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_phoneotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='لطفا شماره موبایل خود را به درستی وارد کنید', regex='^09[0|1|2|3][0-9]{8}$')])),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('expire_at', models.DateTimeField(blank=True)),
                ('resend_at', models.DateTimeField(blank=True)),
                ('count', models.IntegerField(default=0)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
