# Generated by Django 4.0.3 on 2022-07-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_phoneotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
