# Generated by Django 4.0.3 on 2022-08-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_phoneotp_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/users/user.jpg', upload_to='images/users'),
        ),
    ]
