# Generated by Django 4.0.3 on 2022-08-14 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('created_at',)},
        ),
    ]
