# Generated by Django 4.0.3 on 2022-08-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_paymentmethod_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalCode',
            new_name='postal_code',
        ),
    ]
