# Generated by Django 4.0.3 on 2022-08-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_postalcode_shippingaddress_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shippingPrice',
            new_name='shipping_price',
        ),
    ]
