# Generated by Django 4.0.3 on 2022-07-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='other_product_colors',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_products', to='products.productcolor'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.productcolor'),
        ),
    ]
