# Generated by Django 4.0.3 on 2022-07-24 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_other_product_colors_product_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='other_product_colors',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_products', to='products.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.color'),
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
