# Generated by Django 4.0.3 on 2022-07-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_product_other_product_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_colors',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
