# Generated by Django 4.0.3 on 2022-07-24 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productdesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productdesign'),
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='products.color')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='products.productdesign')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.productcolor'),
        ),
    ]
