# Generated by Django 4.0.3 on 2022-07-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_design_productcolor_product_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_code1',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_code2',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
