# Generated by Django 4.0.3 on 2022-07-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='feature',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='ProductKeyValFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('key', 'value')},
            },
        ),
    ]
