# Generated by Django 4.0.3 on 2022-07-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_productfeature_feature_productkeyvalfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key_val_features',
            field=models.ManyToManyField(to='products.productkeyvalfeature'),
        ),
    ]
