# Generated by Django 4.0.3 on 2022-08-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_key_val_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
