# Generated by Django 4.0.3 on 2022-08-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_productreview_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-created_at']},
        ),
    ]
